Handling database migration without depending migrations scripts from external sources (#20)
Handling database migration without depending migrations scripts from
external sources

Closes #7

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -9,36 +9,7 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  check-changes:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: read
-    outputs:
-      backend: ${{ steps.filter.outputs.backend }}
-      frontend: ${{ steps.filter.outputs.frontend }}
-      goreleaser: ${{ steps.filter.outputs.goreleaser }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - uses: dorny/paths-filter@v3
-        id: filter
-        with:
-          token: ${{ github.token }}
-          filters: |
-            backend:
-              - 'backend/**'
-            frontend:
-              - 'frontend/**'
-            goreleaser:
-              - 'backend/.goreleaser.yaml'
-              - 'backend/goreleaser.dockerfile'
-
   backend-unit-test:
-    needs: check-changes
-    if: ${{ needs.check-changes.outputs.backend == 'true' }}
     name: Backend Unit Tests
     runs-on: ubuntu-latest
     steps:
@@ -60,8 +31,6 @@ jobs:
           retention-days: 1
 
   frontend-unit-test:
-    needs: check-changes
-    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
     name: Frontend Unit Tests
     runs-on: ubuntu-latest
     steps:
@@ -114,8 +83,7 @@ jobs:
 
   code-analysis:
     runs-on: ubuntu-latest
-    needs: [check-changes, frontend-unit-test, backend-unit-test]
-    if: ${{ needs.check-changes.outputs.backend == 'true' || needs.check-changes.outputs.frontend == 'true' }}
+    needs: [frontend-unit-test, backend-unit-test]
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -145,8 +113,8 @@ jobs:
   release:
     name: Test Release
     needs:
-      - check-changes
-    if: ${{ needs.check-changes.outputs.goreleaser == 'true' }}
+      - docker-build-and-test-frontend
+      - docker-build-backend
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -176,3 +144,69 @@ jobs:
           workdir: backend
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  docker-build-and-test-frontend:
+    needs:
+      - frontend-unit-test
+    name: Frontend Docker Build and Test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: ./frontend/smarty-pants/
+          file: ./frontend/smarty-pants/Dockerfile
+          push: false
+          load: true
+          tags: frontend:test
+
+      - name: Test Docker image
+        run: |
+          docker run --name test-container -d -p 3000:3000 frontend:test
+          sleep 10  # Give the container time to start up
+
+          # Basic test to check if the server is responding
+          if curl -sSf http://localhost:3000 > /dev/null; then
+            echo "Docker image test passed: Server is responding"
+          else
+            echo "Docker image test failed: Server is not responding"
+            exit 1
+          fi
+
+          docker stop test-container
+          docker rm test-container
+
+      - name: Cleanup
+        if: always()
+        run: docker image rm frontend:test
+
+  docker-build-backend:
+    name: Backend Docker Build
+    needs:
+      - backend-unit-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: ./backend
+          file: ./backend/Dockerfile
+          push: false
+          load: true
+          tags: backend:test
+
+      - name: Cleanup
+        if: always()
+        run: docker image rm backend:test
